name = "Darknet"
uuid = "e2912957-7d06-5673-a7d6-96d153624877"
authors = ["Ian Butterworth <i.r.butterworth@gmail.com"]
version = "0.2.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Darknet_jll = "761d2b37-0f2d-5ad8-be19-54610544a161"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
BinaryProvider = "0.5"
CEnum = "0.2"
Darknet_jll = "2019.11.15"
julia = "1.3"

[extras]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FileIO", "ImageCore", "ImageMagick", "QuartzImageIO", "Test"]
