name = "Darknet"
uuid = "e2912957-7d06-5673-a7d6-96d153624877"
authors = ["Ian Butterworth <i.r.butterworth@gmail.com"]
version = "0.2.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Darknet_jll = "761d2b37-0f2d-5ad8-be19-54610544a161"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
BinaryProvider = "0.5"
CEnum = "0.2"
Darknet_jll = "2019.11.15"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
